In [6]:
# Import
import sys
sys.path.append('../../../')
 
from a_models.general import *   
 
if __name__ == '__main__': 
    # --------------------------------------------------  
    entity  = "jobdescription_dataset_0_5000_fk_train"  
    # -------------------------------------------------- 
    space = "  __" 
    # --------------------------------------------------  
    old_value    = '-	'    
    new_value    = '' 
    updated_and_clean(entity, old_value, new_value, space) 
    # --------------------------------------------------  
    old_value    = '  ' 
    new_value    = '' 
    updated_and_clean(entity, old_value, new_value, space) 
    # --------------------------------------------------  
    old_value    = '-	     ' 
    new_value    = '' 
    updated_and_clean(entity, old_value, new_value, space) 
    # --------------------------------------------------  
    old_value    = 'li style=text-alignjustify' 
    new_value    = '' 
    updated_and_clean(entity, old_value, new_value, space)  
    # --------------------------------------------------  
    old_value    = '-             ' 
    new_value    = '' 
    updated_and_clean(entity, old_value, new_value, space) 
    # --------------------------------------------------  
    old_value    = '-        '  
    new_value    = '' 
    updated_and_clean(entity, old_value, new_value, space) 
    # --------------------------------------------------  
    old_value    = '-  Usia' 
    new_value    = 'Usia' 
    updated_and_clean(entity, old_value, new_value, space) 
    # --------------------------------------------------  
    old_value    = '-Usia' 
    new_value    = 'Usia' 
    updated_and_clean(entity, old_value, new_value, space) 
    # --------------------------------------------------  
    old_value    = '– Usia' 
    new_value    = 'Usia' 
    updated_and_clean(entity, old_value, new_value, space) 
    # --------------------------------------------------  
    old_value    = '- Berusia' 
    new_value    = 'Berusia' 
    updated_and_clean(entity, old_value, new_value, space) 
    # --------------------------------------------------  
    old_value    = '-             Usia' 
    new_value    = 'Usia' 
    updated_and_clean(entity, old_value, new_value, space) 
    # --------------------------------------------------  
    old_value    = '-        Usia' 
    new_value    = 'Usia' 
    updated_and_clean(entity, old_value, new_value, space) 
    # --------------------------------------------------  
    old_value    = '-  Usia' 
    new_value    = 'Usia' 
    updated_and_clean(entity, old_value, new_value, space) 
    # --------------------------------------------------  
    old_value    = '- usia' 
    new_value    = 'Usia' 
    updated_and_clean(entity, old_value, new_value, space) 
    # --------------------------------------------------  
    old_value    = '- Maksimal' 
    new_value    = 'Maksimal' 
    updated_and_clean(entity, old_value, new_value, space) 
    # --------------------------------------------------  
    # old_value    = '- usia' 
    # new_value    = 'Usia' 
    # updated_and_clean(entity, old_value, new_value, space) 
    ####################################################  ##

  ____updated_and_clean()
  ______UPDATE `jobdescription_dataset_0_5000_fk_train` SET  `name`= REPLACE(name, '-	', '')
  ____updated_and_clean()
  ______UPDATE `jobdescription_dataset_0_5000_fk_train` SET  `name`= REPLACE(name, '  ', '')
  ____updated_and_clean()
  ______UPDATE `jobdescription_dataset_0_5000_fk_train` SET  `name`= REPLACE(name, '-	     ', '')
  ____updated_and_clean()
  ______UPDATE `jobdescription_dataset_0_5000_fk_train` SET  `name`= REPLACE(name, 'li style=text-alignjustify', '')
  ____updated_and_clean()
  ______UPDATE `jobdescription_dataset_0_5000_fk_train` SET  `name`= REPLACE(name, '-             ', '')
  ____updated_and_clean()
  ______UPDATE `jobdescription_dataset_0_5000_fk_train` SET  `name`= REPLACE(name, '-        ', '')
  ____updated_and_clean()
  ______UPDATE `jobdescription_dataset_0_5000_fk_train` SET  `name`= REPLACE(name, '-  Usia', 'Usia')
  ____updated_and_clean()
  ______UPDATE `jobdescription_dataset_0_5000_fk_train` SET  `name`= REPLACE(name, '-Usia', 'Usia')
  ____updated_and_clean()
  ______UPDATE `jobdescription_dataset_0_5000_fk_train` SET  `name`= REPLACE(name, '– Usia', 'Usia')
  ____updated_and_clean()
  ______UPDATE `jobdescription_dataset_0_5000_fk_train` SET  `name`= REPLACE(name, '- Berusia', 'Berusia')
  ____updated_and_clean()
  ______UPDATE `jobdescription_dataset_0_5000_fk_train` SET  `name`= REPLACE(name, '-             Usia', 'Usia')
  ____updated_and_clean()
  ______UPDATE `jobdescription_dataset_0_5000_fk_train` SET  `name`= REPLACE(name, '-        Usia', 'Usia')
  ____updated_and_clean()
  ______UPDATE `jobdescription_dataset_0_5000_fk_train` SET  `name`= REPLACE(name, '-  Usia', 'Usia')
  ____updated_and_clean()
  ______UPDATE `jobdescription_dataset_0_5000_fk_train` SET  `name`= REPLACE(name, '- usia', 'Usia')
  ____updated_and_clean()
  ______UPDATE `jobdescription_dataset_0_5000_fk_train` SET  `name`= REPLACE(name, '- Maksimal', 'Maksimal')