In [1]:
# Import
import sys
sys.path.append('../../../')
 
from a_models.annotation import *   
 
if __name__ == '__main__': 
    # --------------------------------------------------  
    entity      = "jobdescription"  
    ner         = "Perempuan"  
    label       = "B-Jenis_kelamin"  
    entitas     = "jenis_kelamin"  
    update      = "yes"  
    # -------------------------------------------------- 
    space = "  __" 
    # --------------------------------------------------  
    wildcard(entity, ner, label, entitas, update, space)
    # --------------------------------------------------    
    ####################################################

  ____wildcard()
  ______Select  id  , name  , label  from jobdescription where name like '%Perempuan%'
  ________Total Row(s) : 94
  ________ner length: 1
  ________label length: 1
  __________[1/94]  Laki - laki / Perempuan usia max 32 tahun
  ____________________  Old len: 9 __ New len: 9
  ____________________  O O O O B-Jenis_kelamin O O O O
  ____________________  O O O O B-Jenis_kelamin O O O O
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='Laki - laki / Perempuan usia max 32 tahun',  `label`='O O O O B-Jenis_kelamin O O O O',  `space_length`='9',  `jenis_kelamin` = 1  WHERE id = '76286'
  ________
  __________[2/94]  - Laki - laki / Perempuan usia max 45 th
  ____________________  Old len: 10 __ New len: 10
  ____________________  O O O O O B-Jenis_kelamin B-Jenis_kelamin O O O
  ____________________  O O O O O B-Jenis_kelamin B-Jenis_kelamin O O O
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='- Laki - laki / Perempuan usia max 45 th',  `label`='O O O O O B-Jenis_kelamin B-Jenis_kelamin O O O',  `space_length`='10',  `jenis_kelamin` = 1  WHERE id = '191664'
  ________
  __________[3/94]  Laki - laki / Perempuan
  ____________________  Old len: 5 __ New len: 5
  ____________________  O O O O B-Jenis_kelamin
  ____________________  O O O O B-Jenis_kelamin
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='Laki - laki / Perempuan',  `label`='O O O O B-Jenis_kelamin',  `space_length`='5',  `jenis_kelamin` = 1  WHERE id = '217647'
  ________
  __________[4/94]  Laki - laki / Perempuan
  ____________________  Old len: 5 __ New len: 5
  ____________________  O O O O B-Jenis_kelamin
  ____________________  O O O O B-Jenis_kelamin
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='Laki - laki / Perempuan',  `label`='O O O O B-Jenis_kelamin',  `space_length`='5',  `jenis_kelamin` = 1  WHERE id = '243836'
  ________
  __________[5/94]  - Laki - laki / Perempuan
  ____________________  Old len: 6 __ New len: 6
  ____________________  O O O O O B-Jenis_kelamin
  ____________________  O O O O O B-Jenis_kelamin
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='- Laki - laki / Perempuan',  `label`='O O O O O B-Jenis_kelamin',  `space_length`='6',  `jenis_kelamin` = 1  WHERE id = '249790'
  ________
  __________[6/94]  laki - laki dan perempuan .
  ____________________  Old len: 6 __ New len: 6
  ____________________  O O O O O O
  ____________________  O O O O B-Jenis_kelamin O
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='laki - laki dan perempuan .',  `label`='O O O O B-Jenis_kelamin O',  `space_length`='6',  `jenis_kelamin` = 1  WHERE id = '253076'
  ________
  __________[7/94]  - Laki - laki / Perempuan
  ____________________  Old len: 6 __ New len: 6
  ____________________  O O O O O B-Jenis_kelamin
  ____________________  O O O O O B-Jenis_kelamin
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='- Laki - laki / Perempuan',  `label`='O O O O O B-Jenis_kelamin',  `space_length`='6',  `jenis_kelamin` = 1  WHERE id = '257590'
  ________
  __________[8/94]  Laki / Perempuan
  ____________________  Old len: 3 __ New len: 3
  ____________________  O O B-Jenis_kelamin
  ____________________  O O B-Jenis_kelamin
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='Laki / Perempuan',  `label`='O O B-Jenis_kelamin',  `space_length`='3',  `jenis_kelamin` = 1  WHERE id = '262787'
  ________
  __________[9/94]  - Laki - laki / Perempuan
  ____________________  Old len: 6 __ New len: 6
  ____________________  O O O O O B-Jenis_kelamin
  ____________________  O O O O O B-Jenis_kelamin
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='- Laki - laki / Perempuan',  `label`='O O O O O B-Jenis_kelamin',  `space_length`='6',  `jenis_kelamin` = 1  WHERE id = '293109'
  ________
  __________[10/94]  laki atau perempuan
  ____________________  Old len: 3 __ New len: 3
  ____________________  O O O
  ____________________  O O B-Jenis_kelamin
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='laki atau perempuan',  `label`='O O B-Jenis_kelamin',  `space_length`='3',  `jenis_kelamin` = 1  WHERE id = '367348'
  ________
  __________[11/94]  - laki - laki dan perempuan - usia maksimal 26 tahun - pendidikan min SMA / SMK - memiliki pengalaman di bidang yang sama - mampu bekerja di bawah tekanan - mampu berkomunikasi dengan baik - Berpenampilan rapi
  ____________________  Old len: 38 __ New len: 38
  ____________________  O O O O O O O O O O O O O O O B-Tingkat_pendidikan O B-Tingkat_pendidikan O O O O O O O O O O O O O O O O O O O O
  ____________________  O O O O O B-Jenis_kelamin O O O O O O O O O B-Tingkat_pendidikan O B-Tingkat_pendidikan O O O O O O O O O O O O O O O O O O O O
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='- laki - laki dan perempuan - usia maksimal 26 tahun - pendidikan min SMA / SMK - memiliki pengalaman di bidang yang sama - mampu bekerja di bawah tekanan - mampu berkomunikasi dengan baik - Berpenampilan rapi',  `label`='O O O O O B-Jenis_kelamin O O O O O O O O O B-Tingkat_pendidikan O B-Tingkat_pendidikan O O O O O O O O O O O O O O O O O O O O',  `space_length`='38',  `jenis_kelamin` = 1  WHERE id = '600761'
  ________
  __________[12/94]  Laki - laki / Perempuan
  ____________________  Old len: 5 __ New len: 5
  ____________________  O O O O B-Jenis_kelamin
  ____________________  O O O O B-Jenis_kelamin
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='Laki - laki / Perempuan',  `label`='O O O O B-Jenis_kelamin',  `space_length`='5',  `jenis_kelamin` = 1  WHERE id = '630750'
  ________
  __________[13/94]  laki - laki dan perempuan .
  ____________________  Old len: 6 __ New len: 6
  ____________________  O O O O O O
  ____________________  O O O O B-Jenis_kelamin O
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='laki - laki dan perempuan .',  `label`='O O O O B-Jenis_kelamin O',  `space_length`='6',  `jenis_kelamin` = 1  WHERE id = '637201'
  ________
  __________[14/94]  laki atau perempuan silahkan melamar .
  ____________________  Old len: 6 __ New len: 6
  ____________________  O O O O O O
  ____________________  O O B-Jenis_kelamin O O O
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='laki atau perempuan silahkan melamar .',  `label`='O O B-Jenis_kelamin O O O',  `space_length`='6',  `jenis_kelamin` = 1  WHERE id = '662380'
  ________
  __________[15/94]  Laki - laki / Perempuan usia max 32 tahun
  ____________________  Old len: 9 __ New len: 9
  ____________________  O O O O B-Jenis_kelamin O O O O
  ____________________  O O O O B-Jenis_kelamin O O O O
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='Laki - laki / Perempuan usia max 32 tahun',  `label`='O O O O B-Jenis_kelamin O O O O',  `space_length`='9',  `jenis_kelamin` = 1  WHERE id = '676274'
  ________
  __________[16/94]  Laki - laki / Perempuan usia maks .
  ____________________  Old len: 8 __ New len: 8
  ____________________  O O O O B-Jenis_kelamin O O O
  ____________________  O O O O B-Jenis_kelamin O O O
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='Laki - laki / Perempuan usia maks .',  `label`='O O O O B-Jenis_kelamin O O O',  `space_length`='8',  `jenis_kelamin` = 1  WHERE id = '740310'
  ________
  __________[17/94]  Perempuan max usia 26 th Pendidikan min SMK / SMA Sederajat Disiplin dan Pekerja Keras Teliti , Jujur , dan Bertanggung Paham Microsoft Excel Jawab Memahami Social Media Mahir menggunakan aplikasi shopee Mahir mengedit Video Menguasai aplikasi CAPCUT Kreatif & Komunikatif
  ____________________  Old len: 41 __ New len: 41
  ____________________  B-Jenis_kelamin O O O O O O B-Tingkat_pendidikan O B-Tingkat_pendidikan O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O
  ____________________  B-Jenis_kelamin O O O O O O B-Tingkat_pendidikan O B-Tingkat_pendidikan O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='Perempuan max usia 26 th Pendidikan min SMK / SMA Sederajat Disiplin dan Pekerja Keras Teliti , Jujur , dan Bertanggung Paham Microsoft Excel Jawab Memahami Social Media Mahir menggunakan aplikasi shopee Mahir mengedit Video Menguasai aplikasi CAPCUT Kreatif & Komunikatif',  `label`='B-Jenis_kelamin O O O O O O B-Tingkat_pendidikan O B-Tingkat_pendidikan O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O',  `space_length`='41',  `jenis_kelamin` = 1  WHERE id = '742583'
  ________
  __________[18/94]  Menganalisa tren untuk memastikan konten yang dibuat berkualitas Kualifikasi : - Perempuan - Pendidikan min SMA Sederajat - Usia max 27 tahun - Punya skil : Editing video Fotografi Videografi - Terbiasa membuat konten ( Tiktok , IG reels ) - Berani tampil depan kamera - Kreatif , komunikatif
  ____________________  Old len: 49 __ New len: 49
  ____________________  O O O O O O O O O O O B-Jenis_kelamin O O O B-Tingkat_pendidikan O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O
  ____________________  O O O O O O O O O O O B-Jenis_kelamin O O O B-Tingkat_pendidikan O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='Menganalisa tren untuk memastikan konten yang dibuat berkualitas Kualifikasi : - Perempuan - Pendidikan min SMA Sederajat - Usia max 27 tahun - Punya skil : Editing video Fotografi Videografi - Terbiasa membuat konten ( Tiktok , IG reels ) - Berani tampil depan kamera - Kreatif , komunikatif',  `label`='O O O O O O O O O O O B-Jenis_kelamin O O O B-Tingkat_pendidikan O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O',  `space_length`='49',  `jenis_kelamin` = 1  WHERE id = '744393'
  ________
  __________[19/94]  Laki - laki / Perempuan
  ____________________  Old len: 5 __ New len: 5
  ____________________  O O O O B-Jenis_kelamin
  ____________________  O O O O B-Jenis_kelamin
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='Laki - laki / Perempuan',  `label`='O O O O B-Jenis_kelamin',  `space_length`='5',  `jenis_kelamin` = 1  WHERE id = '744427'
  ________
  __________[20/94]  Laki - laki atau Perempuan
  ____________________  Old len: 5 __ New len: 5
  ____________________  O O O O B-Jenis_kelamin
  ____________________  O O O O B-Jenis_kelamin
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='Laki - laki atau Perempuan',  `label`='O O O O B-Jenis_kelamin',  `space_length`='5',  `jenis_kelamin` = 1  WHERE id = '745485'
  ________
  __________[21/94]  jenis kelamin / laki2 / perempuan ; laki dan perempuan 2 .
  ____________________  Old len: 12 __ New len: 12
  ____________________  O O O O O O O O O O O O
  ____________________  O O O O O B-Jenis_kelamin O O O B-Jenis_kelamin O O
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='jenis kelamin / laki2 / perempuan ; laki dan perempuan 2 .',  `label`='O O O O O B-Jenis_kelamin O O O B-Jenis_kelamin O O',  `space_length`='12',  `jenis_kelamin` = 1  WHERE id = '746153'
  ________
  __________[22/94]  Laki - laki / Perempuan
  ____________________  Old len: 5 __ New len: 5
  ____________________  O O O O B-Jenis_kelamin
  ____________________  O O O O B-Jenis_kelamin
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='Laki - laki / Perempuan',  `label`='O O O O B-Jenis_kelamin',  `space_length`='5',  `jenis_kelamin` = 1  WHERE id = '747240'
  ________
  __________[23/94]  Laki - laki / Perempuan
  ____________________  Old len: 5 __ New len: 5
  ____________________  O O O O B-Jenis_kelamin
  ____________________  O O O O B-Jenis_kelamin
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='Laki - laki / Perempuan',  `label`='O O O O B-Jenis_kelamin',  `space_length`='5',  `jenis_kelamin` = 1  WHERE id = '747654'
  ________
  __________[24/94]  Laki - laki / Perempuan
  ____________________  Old len: 5 __ New len: 5
  ____________________  O O O O B-Jenis_kelamin
  ____________________  O O O O B-Jenis_kelamin
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='Laki - laki / Perempuan',  `label`='O O O O B-Jenis_kelamin',  `space_length`='5',  `jenis_kelamin` = 1  WHERE id = '748759'
  ________
  __________[25/94]  anak perempuan berusia 2 tahun .
  ____________________  Old len: 6 __ New len: 6
  ____________________  O O O O O O
  ____________________  O B-Jenis_kelamin O O O O
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='anak perempuan berusia 2 tahun .',  `label`='O B-Jenis_kelamin O O O O',  `space_length`='6',  `jenis_kelamin` = 1  WHERE id = '749581'
  ________
  __________[26/94]  Laki - laki / Perempuan 2 .
  ____________________  Old len: 7 __ New len: 7
  ____________________  O O O O B-Jenis_kelamin O O
  ____________________  O O O O B-Jenis_kelamin O O
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='Laki - laki / Perempuan 2 .',  `label`='O O O O B-Jenis_kelamin O O',  `space_length`='7',  `jenis_kelamin` = 1  WHERE id = '750605'
  ________
  __________[27/94]  - Bertanggung jawab terhadap stock produk - Membersihkan cafe dan menjaga kebersihan cafe - Menangani dan mengelola customer - Pria / Wanita - Tanpa Pengalaman Bekerja - SMA / SMK - 19 - 29 Tahun - Kandidat wajib upload foto - Terima kandidat dari mana saja Persyaratan Lainnya : - Laki - Laki / Perempuan maksimal usia 29 tahun - Memiliki pengalaman sebagai Server atau Waiter lebih disukai - Minimal SMA / SMK - Fresh graduate dipersilakan melamar - Sudah Vaksinasi Covid 19 Booster 1 - Periode kerja 12 Juli 2023 - 1 Agustus 2023 - Penempatan : Cafe Haagen - Dazs Tunjungan Plaza
  ____________________  Old len: 102 __ New len: 104 __ WARNING!
  ____________________  O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O B-Tingkat_pendidikan O O O O O O O O O O O O O O O O O O O O O O O B-Jenis_kelamin O O O O O O O O O O O O O O O O O O B-Tingkat_pendidikan O O O O O O O O O O O O O O O O O O O O O O O O O O O O
  ____________________  O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='- Bertanggung jawab terhadap stock produk - Membersihkan cafe dan menjaga kebersihan cafe - Menangani dan mengelola customer - Pria / Wanita - Tanpa Pengalaman Bekerja - SMA / SMK - 19 - 29 Tahun - Kandidat wajib upload foto - Terima kandidat dari mana saja Persyaratan Lainnya : - Laki - Laki / Perempuan maksimal usia 29 tahun - Memiliki pengalaman sebagai Server atau Waiter lebih disukai - Minimal SMA / SMK - Fresh graduate dipersilakan melamar - Sudah Vaksinasi Covid 19 Booster 1 - Periode kerja 12 Juli 2023 - 1 Agustus 2023 - Penempatan : Cafe Haagen - Dazs Tunjungan Plaza',  `label`='O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O',  `space_length`='104',  `jenis_kelamin` = 1  WHERE id = '751501'
  ________
  __________[28/94]  Laki - laki / Perempuan
  ____________________  Old len: 5 __ New len: 5
  ____________________  O O O O B-Jenis_kelamin
  ____________________  O O O O B-Jenis_kelamin
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='Laki - laki / Perempuan',  `label`='O O O O B-Jenis_kelamin',  `space_length`='5',  `jenis_kelamin` = 1  WHERE id = '752908'
  ________
  __________[29/94]  Perempuan / Laki - laki Umur Max .
  ____________________  Old len: 8 __ New len: 8
  ____________________  B-Jenis_kelamin O O O O O O O
  ____________________  B-Jenis_kelamin O O O O O O O
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='Perempuan / Laki - laki Umur Max .',  `label`='B-Jenis_kelamin O O O O O O O',  `space_length`='8',  `jenis_kelamin` = 1  WHERE id = '757616'
  ________
  __________[30/94]  Laki - laki / Perempuan
  ____________________  Old len: 5 __ New len: 5
  ____________________  O O O O B-Jenis_kelamin
  ____________________  O O O O B-Jenis_kelamin
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='Laki - laki / Perempuan',  `label`='O O O O B-Jenis_kelamin',  `space_length`='5',  `jenis_kelamin` = 1  WHERE id = '757762'
  ________
  __________[31/94]  Jenis Kelamin Laki - Laki / Perempuan 4 .
  ____________________  Old len: 9 __ New len: 9
  ____________________  O O O O O O B-Jenis_kelamin O O
  ____________________  O O O O O O B-Jenis_kelamin O O
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='Jenis Kelamin Laki - Laki / Perempuan 4 .',  `label`='O O O O O O B-Jenis_kelamin O O',  `space_length`='9',  `jenis_kelamin` = 1  WHERE id = '761311'
  ________
  __________[32/94]  Laki - laki / Perempuan
  ____________________  Old len: 5 __ New len: 5
  ____________________  O O O O B-Jenis_kelamin
  ____________________  O O O O B-Jenis_kelamin
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='Laki - laki / Perempuan',  `label`='O O O O B-Jenis_kelamin',  `space_length`='5',  `jenis_kelamin` = 1  WHERE id = '763325'
  ________
  __________[33/94]  Laki - laki / Perempuan
  ____________________  Old len: 5 __ New len: 5
  ____________________  O O O O B-Jenis_kelamin
  ____________________  O O O O B-Jenis_kelamin
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='Laki - laki / Perempuan',  `label`='O O O O B-Jenis_kelamin',  `space_length`='5',  `jenis_kelamin` = 1  WHERE id = '769376'
  ________
  __________[34/94]  Perempuan dan Good Looking
  ____________________  Old len: 4 __ New len: 4
  ____________________  B-Jenis_kelamin O O O
  ____________________  B-Jenis_kelamin O O O
  __________updated_data_val()
  ____________UPDATE `jobdescription` SET  `name`='Perempuan dan Good Looking',  `label`='B-Jenis_kelamin O O O',  `space_length`='4',  `jenis_kelamin` = 1  WHERE id = '773504'
  ________
  __________[35/94]  - Membuat daily content - Bertanggung jawab selama proses pembuatan konten ( proses perekaman , editing hingga tayang di media sosial ) - Memberikan report terhadap konten - konten yang dijalankan - Menganalisa tren untuk memastikan konten yang dibuat berkualitas Tidak sedang sekolah / kuliah atau kerja Laki - laki / Perempuan maks .
  ____________________  Old len: 54 __ New len: 54
  ____________________  O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O B-Jenis_kelamin B-Jenis_kelamin O
  ____________________  O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O B-Jenis_kelamin B-Jenis_kelamin O
  __________updated_data_val()