In [2]:
# Import
import sys
sys.path.append('../../../../')
 
from a_models.general import *   
 
if __name__ == '__main__': 
    # --------------------------------------------------  
    entity  = "jobdescription"  
    # -------------------------------------------------- 
    space = "  __" 
    # --------------------------------------------------  
    update_clean_and_replace(entity, space)
    # --------------------------------------------------   
    ####################################################

  ______Select  old   , new   from replace_strings
  ________Total Row(s) : 30
  __________[1/30]  #u002F __ /
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, 'u002F', '/')
  __________[2/30]  #u003C __ <
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, 'u003C', '<')
  __________[3/30]  #u003E __ >
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, 'u003E', '>')
  __________[4/30]  #</li> __
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, '</li>', ' ')
  __________[5/30]  #</ul> __
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, '</ul>', ' ')
  __________[6/30]  #<ul> __
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, '<ul>', ' ')
  __________[7/30]  #<li> __
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, '<li>', ' ')
  __________[8/30]  #</p> __
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, '</p>', ' ')
  __________[9/30]  #<p> __
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, '<p>', ' ')
  __________[10/30]  #</ol> __
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, '</ol>', ' ')
  __________[11/30]  #<ol> __
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, '<ol>', ' ')
  __________[12/30]  #</strong> __
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, '</strong>', ' ')
  __________[13/30]  #<strong> __
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, '<strong>', ' ')
  __________[14/30]  #</u> __
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, '</u>', ' ')
  __________[15/30]  #<u> __
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, '<u>', ' ')
  __________[16/30]  #</div> __
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, '</div>', ' ')
  __________[17/30]  #<div> __
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, '<div>', ' ')
  __________[18/30]  #</b> __
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, '</b>', ' ')
  __________[19/30]  #<b> __
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, '<b>', ' ')
  __________[20/30]  #<br /> __
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, '<br />', ' ')
  __________[21/30]  #&amp; __  &
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, '&amp;', ' & ')
  __________[22/30]  #</em> __
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, '</em>', ' ')
  __________[23/30]  #<em> __
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, '<em>', ' ')
  __________[24/30]  #&lt; __
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, '&lt;', ' ')
  __________[25/30]  #&gt; __
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, '&gt;', ' ')
  __________[26/30]  #<li style="margin-left:30px"> __
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, '<li style="margin-left:30px">', ' ')
  __________[27/30]  #<div style="text-align:justify"> __
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, '<div style="text-align:justify">', ' ')
  __________[28/30]  #> __
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, '>', ' ')
  __________[29/30]  #• __
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, '•', ' ')
  __________[30/30]  #< __
  __________updated_and_clean()
  ____________UPDATE `jobdescription` SET  `name`= REPLACE(name, '<', ' ')