In [1]:
# Import
import sys
sys.path.append('../../../../')
 
from a_models.general import *   
 
if __name__ == '__main__': 
    # --------------------------------------------------  
    entity              = "working_hours"  
    entity_extract      = "benefits"  
    entity_destination  = "jobtitle"  
    attr                = "working_hours_id"
    # -------------------------------------------------- 
    space = "  __" 
    # --------------------------------------------------  
    extract_entity(entity, entity_extract, entity_destination, attr, space)
    # --------------------------------------------------   
    ####################################################

  ____extract_entity()
  ______Select  id   , nama   from dataset_working_hours
  ________Total Row(s) : 1
  __________[1/1]  #Waktu Regular, Senin - Jumat
  __________select_entity()
  ____________Select  fk_id   , name   from benefits WHERE `name` LIKE '%Waktu Regular, Senin - Jumat%'
  ______________Total Row(s) : 19039
  ________________[1/19039]  #1 __ Asuransi Gigi,Tip,Asuransi kesehatan,Penglihatan,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '1'
  ________________[2/19039]  #2 __ Asuransi kesehatan,Waktu regular, Senin - Jumat,Formil (contoh: Kemeja + Dasi)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '2'
  ________________[3/19039]  #10 __ Waktu regular, Senin - Jumat,Kasual (contoh: Kaos)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '10'
  ________________[4/19039]  #12 __ Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja),-
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '12'
  ________________[5/19039]  #15 __ Tip,Asuransi kesehatan,Parkir,Waktu regular, Senin - Jumat,Kasual (contoh: Kaos),DPLK, Annual Bonus, Training, Car / Motorcycle Ownership Program
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '15'
  ________________[6/19039]  #17 __ Asuransi kesehatan,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '17'
  ________________[7/19039]  #18 __ Tunjangan Pendidikan,Tip,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '18'
  ________________[8/19039]  #19 __ Asuransi Gigi,Tunjangan Pendidikan,Asuransi kesehatan,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '19'
  ________________[9/19039]  #20 __ Tip,Asuransi kesehatan,Pinjaman,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja),BPJS Kesehatan, Tenaga Kerja, Pensiun, Insurance
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '20'
  ________________[10/19039]  #24 __ Asuransi kesehatan,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja),16 days annual leave, THR, Meal Allowance.
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '24'
  ________________[11/19039]  #27 __ Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja),BPJS Ketenagakerjaan & BPJS Kesehatan
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '27'
  ________________[12/19039]  #29 __ Asuransi Gigi,Asuransi kesehatan,Olahraga (contoh: pusat kebugaran),Parkir,Waktu regular, Senin - Jumat,Performance Incentive Scheme,Business, Casual
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '29'
  ________________[13/19039]  #31 __ Tip,Asuransi kesehatan,Parkir,Waktu regular, Senin - Jumat,Kasual (contoh: Kaos),Makan, BPJS Ketenagakerjaan
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '31'
  ________________[14/19039]  #33 __ Tip,Asuransi kesehatan,Waktu regular, Senin - Jumat,Formil (contoh: Kemeja + Dasi)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '33'
  ________________[15/19039]  #34 __ Asuransi kesehatan,Waktu regular, Senin - Jumat,Kasual (contoh: Kaos)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '34'
  ________________[16/19039]  #36 __ Asuransi Gigi,Tip,Asuransi kesehatan,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '36'
  ________________[17/19039]  #37 __ Tip,Parkir,Waktu regular, Senin - Jumat,Formil (contoh: Kemeja + Dasi),BPJS
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '37'
  ________________[18/19039]  #39 __ Tunjangan Pendidikan,Tip,Asuransi kesehatan,Pinjaman,Olahraga (contoh: pusat kebugaran),Waktu regular, Senin - Jumat,Kasual (contoh: Kaos)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '39'
  ________________[19/19039]  #41 __ Tip,Waktu regular, Senin - Jumat,Kasual (contoh: Kaos)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '41'
  ________________[20/19039]  #42 __ Asuransi kesehatan,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '42'
  ________________[21/19039]  #43 __ Asuransi Gigi,Asuransi kesehatan,Waktu regular, Senin - Jumat,Formil (contoh: Kemeja + Dasi)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '43'
  ________________[22/19039]  #44 __ Asuransi kesehatan,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '44'
  ________________[23/19039]  #51 __ Tip,Asuransi kesehatan,Waktu regular, Senin - Jumat,uniform
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '51'
  ________________[24/19039]  #52 __ Asuransi kesehatan,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '52'
  ________________[25/19039]  #53 __ Asuransi kesehatan,Parkir,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '53'
  ________________[26/19039]  #55 __ Asuransi Gigi,Tunjangan Pendidikan,Tip,Asuransi kesehatan,Penglihatan,Waktu regular, Senin - Jumat,Kasual (contoh: Kaos)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '55'
  ________________[27/19039]  #58 __ Asuransi kesehatan,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '58'
  ________________[28/19039]  #59 __ Tip,Asuransi kesehatan,Parkir,Waktu regular, Senin - Jumat,Uniform
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '59'
  ________________[29/19039]  #62 __ Waktu regular, Senin - Jumat,BPJS, PPH21,Smart Casual
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '62'
  ________________[30/19039]  #65 __ Parkir,Waktu regular, Senin - Jumat
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '65'
  ________________[31/19039]  #66 __ Tip,Asuransi kesehatan,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '66'
  ________________[32/19039]  #67 __ Asuransi kesehatan,Waktu regular, Senin - Jumat,Formil (contoh: Kemeja + Dasi)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '67'
  ________________[33/19039]  #68 __ Asuransi Gigi,Asuransi kesehatan,Parkir,Penglihatan,Waktu regular, Senin - Jumat,Kasual (contoh: Kaos)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '68'
  ________________[34/19039]  #69 __ Asuransi kesehatan,Penglihatan,Waktu regular, Senin - Jumat
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '69'
  ________________[35/19039]  #70 __ Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '70'
  ________________[36/19039]  #71 __ Tunjangan Pendidikan,Tip,Asuransi kesehatan,Parkir,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '71'
  ________________[37/19039]  #74 __ Asuransi kesehatan,Waktu regular, Senin - Jumat,Formil (contoh: Kemeja + Dasi),Ketenagakerjaan, Tempat tinggal (Mess Guru), Tiket Pesawat dsb
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '74'
  ________________[38/19039]  #77 __ Asuransi kesehatan,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '77'
  ________________[39/19039]  #81 __ Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja),will be discused later
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '81'
  ________________[40/19039]  #82 __ Asuransi kesehatan,Pinjaman,Waktu regular, Senin - Jumat
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '82'
  ________________[41/19039]  #83 __ Asuransi kesehatan,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '83'
  ________________[42/19039]  #84 __ Tip,Asuransi kesehatan,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '84'
  ________________[43/19039]  #88 __ Tip,Asuransi kesehatan,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '88'
  ________________[44/19039]  #90 __ Tip,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '90'
  ________________[45/19039]  #91 __ Tip,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '91'
  ________________[46/19039]  #92 __ Asuransi kesehatan,Olahraga (contoh: pusat kebugaran),Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '92'
  ________________[47/19039]  #93 __ Tip,Waktu regular, Senin - Jumat,Kasual (contoh: Kaos)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '93'
  ________________[48/19039]  #95 __ Asuransi kesehatan,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '95'
  ________________[49/19039]  #96 __ Waktu regular, Senin - Jumat,Kasual (contoh: Kaos),Based on performance
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '96'
  ________________[50/19039]  #99 __ Asuransi kesehatan,Waktu regular, Senin - Jumat,Formil (contoh: Kemeja + Dasi)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '99'
  ________________[51/19039]  #102 __ Asuransi Gigi,Tip,Asuransi kesehatan,Pinjaman,Olahraga (contoh: pusat kebugaran),Penglihatan,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '102'
  ________________[52/19039]  #103 __ Asuransi kesehatan,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja),Jamsostek
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '103'
  ________________[53/19039]  #104 __ Asuransi kesehatan,Olahraga (contoh: pusat kebugaran),Parkir,Waktu regular, Senin - Jumat,Formil (contoh: Kemeja + Dasi)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '104'
  ________________[54/19039]  #105 __ Tip,Waktu regular, Senin - Jumat,Kasual (contoh: Kaos)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '105'
  ________________[55/19039]  #112 __ Tip,Asuransi kesehatan,Parkir,Waktu regular, Senin - Jumat,Formil (contoh: Kemeja + Dasi)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '112'
  ________________[56/19039]  #114 __ Asuransi kesehatan,Parkir,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '114'
  ________________[57/19039]  #119 __ Asuransi Gigi,Asuransi kesehatan,Waktu regular, Senin - Jumat,Formil (contoh: Kemeja + Dasi)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '119'
  ________________[58/19039]  #120 __ Asuransi kesehatan,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '120'
  ________________[59/19039]  #122 __ Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '122'
  ________________[60/19039]  #123 __ Tip,Waktu regular, Senin - Jumat,Kasual (contoh: Kaos)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '123'
  ________________[61/19039]  #124 __ Tip,Waktu regular, Senin - Jumat,Kasual (contoh: Kaos)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '124'
  ________________[62/19039]  #125 __ Asuransi kesehatan,Waktu regular, Senin - Jumat,uniform
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '125'
  ________________[63/19039]  #126 __ Asuransi Gigi,Asuransi kesehatan,Pinjaman,Penglihatan,Waktu regular, Senin - Jumat,Tax Allowance, Transportation Allowance, Meals,Uniform
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '126'
  ________________[64/19039]  #128 __ Tip,Asuransi kesehatan,Parkir,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '128'
  ________________[65/19039]  #129 __ Asuransi Gigi,Asuransi kesehatan,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '129'
  ________________[66/19039]  #130 __ Asuransi kesehatan,Waktu regular, Senin - Jumat,Formil (contoh: Kemeja + Dasi)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '130'
  ________________[67/19039]  #132 __ Tip,Parkir,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '132'
  ________________[68/19039]  #134 __ Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '134'
  ________________[69/19039]  #135 __ Asuransi Gigi,Asuransi kesehatan,Pinjaman,Penglihatan,Waktu regular, Senin - Jumat,Tax Allowance, Transportation Allowance, Meals,Uniform
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '135'
  ________________[70/19039]  #136 __ Asuransi Gigi,Tip,Asuransi kesehatan,Parkir,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja),Tunjangan Komunikasi , Bonus Performance
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '136'
  ________________[71/19039]  #138 __ Asuransi kesehatan,Parkir,Waktu regular, Senin - Jumat
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '138'
  ________________[72/19039]  #139 __ Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja),Medical, Training & Transport
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '139'
  ________________[73/19039]  #140 __ Asuransi kesehatan,Parkir,Waktu regular, Senin - Jumat,Formil (contoh: Kemeja + Dasi)
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '140'
  ________________[74/19039]  #141 __ Asuransi kesehatan,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja),Bonus
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '141'
  ________________[75/19039]  #142 __ Asuransi kesehatan,Waktu regular, Senin - Jumat,Business, Uniform
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '142'
  ________________[76/19039]  #144 __ Tip,Asuransi kesehatan,Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja),Attractive Salary, THR, BPJS, Annual & Sick Leaves
  ________________updated_data_id_from_dataset()
  __________________UPDATE `jobtitle` SET  `working_hours_id`='1'  WHERE fk_id = '144'
  ________________[77/19039]  #148 __ Waktu regular, Senin - Jumat,Bisnis (contoh: Kemeja),BPJS Ketenagakerjaan & BPJS Kesehatan
  ________________updated_data_id_from_dataset()

KeyboardInterrupt: